export const EmployeeModel = {
  EmployeeCode: null,
  FirstName: null,
  LastName: null,
  FullName: null,
  Gender: 2,
  DateOfBirth: null,
  PhoneNumber: null,
  Email: null,
  Address: null,
  IdentityNumber: null,
  IdentityDate: null,
  IdentityPlace: null,
  JoinDate: null,
  MartialStatus: null,
  EducationalBackground: null,
  QualificationId: "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  DepartmentId: "17120d02-6ab5-3e43-18cb-66948daf6128",
  PositionId: "548dce5f-5f29-4617-725d-e2ec561b0f41",
  WorkStatus: null,
  PersonalTaxCode: null,
  Salary: null,
  PositionCode: null,
  PositionName: null,
  DepartmentCode: null,
  DepartmentName: null,
  QualificationName: null,
};
