export const EmployeeModel = {
  EmployeeCode: null,
  FirstName: null,
  LastName: null,
  FullName: null,
  Gender: 2,
  DateOfBirth: null,
  PhoneNumber: null,
  Email: null,
  Address: null,
  IdentityNumber: null,
  IdentityDate: null,
  IdentityPlace: null,
  JoinDate: null,
  MartialStatus: null,
  EducationalBackground: null,
  QualificationId: null,
  DepartmentId: null,
  PositionId: null,
  WorkStatus: null,
  PersonalTaxCode: null,
  Salary: null,
  PositionCode: null,
  PositionName: null,
  DepartmentCode: null,
  DepartmentName: null,
  QualificationName: null,
};
